### ISSUE TITLE
Impossible de scroller verticalement

### ISSUE THREAD

**Issue by alphakahere** [GalsenDev221/hacktoberfest.quiz.2023#36]

**Comment by lucien-loua** [comment]
hey @alphakahere c'est due au overflow-y: hidden, j'ai un un PR pour corriger ça.

**Comment by alphakahere** [comment]
Hey @xyhomi3, c'est déjà  fixé

**Comment by lucien-loua** [comment]
Oui je viens de remarquer, mais ça devrais ressembler a ceci sans l'effet de scroll vertical
![Screen Shot 2023-10-30 at 11 07 39](https://github.com/GalsenDev221/hacktoberfest.quiz.2023/assets/82377686/1509baf5-b2cb-45c4-b42f-ff142ff849a0)
@alphakahere

**Comment by daoodaba975** [comment]
Super @xyhomi3 
Tu peux essayer de revoir ton PR #39 y'a des conflits à résoudre, tu peux récupérer d'abord les modification qui ont été faites.

**Comment by lucien-loua** [comment]
> Super @xyhomi3 
> 
> Tu peux essayer de revoir ton PR #39 y'a des conflits à résoudre, tu peux récupérer d'abord les modification qui ont été faites.
> Ok j'aurai besoin d'aide pour les steps à suivre 
>

**Comment by alphakahere** [comment]
> > Super @xyhomi3
> > Tu peux essayer de revoir ton PR #39 y'a des conflits à résoudre, tu peux récupérer d'abord les modification qui ont été faites.
> > Ok j'aurai besoin d'aide pour les steps à suivre

De quoi as-tu besoin @xyhomi3 ?

**Comment by lucien-loua** [comment]
Comme

> > > Super @xyhomi3
> > > Tu peux essayer de revoir ton PR #39 y'a des conflits à résoudre, tu peux récupérer d'abord les modification qui ont été faites.
> > > Ok j'aurai besoin d'aide pour les steps à suivre
> 
> De quoi as-tu besoin @xyhomi3 ?
Comment repair le pull PR agit avec les modifs

**Comment by lucien-loua** [comment]
Nice 🥂
