### ISSUE TITLE
Gestion de Scores Avancée 🔴

### ISSUE THREAD

**Issue by daoodaba975** [GalsenDev221/hacktoberfest.quiz.2023#6]
Développer un tableau des meilleurs scores, une fonction de sauvegarde des scores, ou un classement en ligne.

**Comment by saloum45** [comment]
je peux mettre en place une logique qui permet de stocker l'ensemble des score de l'utilisateur dans le localStorage et un menu qui lui permet d'afficher la liste de ses scores
